"""Fix prescription uploaded_at default with NOW()

Revision ID: 56ae131a5593
Revises: 71302fa9bfb4
Create Date: 2026-07-25 15:22:57.434952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56ae131a5593'
down_revision: Union[str, Sequence[str], None] = '71302fa9bfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_results', 'medicine_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ai_results', 'abbreviations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ai_results', 'roman_urdu',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               nullable=True)
    op.alter_column('ai_results', 'medication_schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ai_results', 'unreadable_sections',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_ai_results_prescription_id'), table_name='ai_results')
    op.create_index('idx_ai_prescription_id', 'ai_results', ['prescription_id'], unique=False)
    op.create_unique_constraint(None, 'ai_results', ['prescription_id'])
    op.drop_constraint(op.f('ai_results_prescription_id_fkey'), 'ai_results', type_='foreignkey')
    op.create_foreign_key(None, 'ai_results', 'prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_history', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_history', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_history_prescription_id'), table_name='chat_history')
    op.create_index('idx_chat_created_at', 'chat_history', ['created_at'], unique=False)
    op.create_index('idx_chat_prescription_id', 'chat_history', ['prescription_id'], unique=False)
    op.drop_constraint(op.f('chat_history_prescription_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ocr_results', 'extracted_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ocr_results_prescription_id'), table_name='ocr_results')
    op.create_index('idx_ocr_prescription_id', 'ocr_results', ['prescription_id'], unique=False)
    op.create_unique_constraint(None, 'ocr_results', ['prescription_id'])
    op.drop_constraint(op.f('ocr_results_prescription_id_fkey'), 'ocr_results', type_='foreignkey')
    op.create_foreign_key(None, 'ocr_results', 'prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.create_index('idx_prescription_uploaded_at', 'prescriptions', ['uploaded_at'], unique=False)
    op.create_index('idx_prescription_user_id', 'prescriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('prescriptions_user_id_fkey'), 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key(op.f('prescriptions_user_id_fkey'), 'prescriptions', 'users', ['user_id'], ['id'])
    op.drop_index('idx_prescription_user_id', table_name='prescriptions')
    op.drop_index('idx_prescription_uploaded_at', table_name='prescriptions')
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.drop_constraint(None, 'ocr_results', type_='foreignkey')
    op.create_foreign_key(op.f('ocr_results_prescription_id_fkey'), 'ocr_results', 'prescriptions', ['prescription_id'], ['id'])
    op.drop_constraint(None, 'ocr_results', type_='unique')
    op.drop_index('idx_ocr_prescription_id', table_name='ocr_results')
    op.create_index(op.f('ix_ocr_results_prescription_id'), 'ocr_results', ['prescription_id'], unique=True)
    op.alter_column('ocr_results', 'extracted_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_prescription_id_fkey'), 'chat_history', 'prescriptions', ['prescription_id'], ['id'])
    op.drop_index('idx_chat_prescription_id', table_name='chat_history')
    op.drop_index('idx_chat_created_at', table_name='chat_history')
    op.create_index(op.f('ix_chat_history_prescription_id'), 'chat_history', ['prescription_id'], unique=False)
    op.alter_column('chat_history', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_history', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'ai_results', type_='foreignkey')
    op.create_foreign_key(op.f('ai_results_prescription_id_fkey'), 'ai_results', 'prescriptions', ['prescription_id'], ['id'])
    op.drop_constraint(None, 'ai_results', type_='unique')
    op.drop_index('idx_ai_prescription_id', table_name='ai_results')
    op.create_index(op.f('ix_ai_results_prescription_id'), 'ai_results', ['prescription_id'], unique=True)
    op.alter_column('ai_results', 'unreadable_sections',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_results', 'medication_schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_results', 'roman_urdu',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_results', 'abbreviations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_results', 'medicine_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
