"""Add indexes

Revision ID: 71302fa9bfb4
Revises: c8721e2d39db
Create Date: 2026-07-25 14:21:09.589532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71302fa9bfb4'
down_revision: Union[str, Sequence[str], None] = 'c8721e2d39db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_results_prescription_id_key'), 'ai_results', type_='unique')
    op.create_index(op.f('ix_ai_results_prescription_id'), 'ai_results', ['prescription_id'], unique=True)
    op.create_index(op.f('ix_chat_history_prescription_id'), 'chat_history', ['prescription_id'], unique=False)
    op.drop_constraint(op.f('ocr_results_prescription_id_key'), 'ocr_results', type_='unique')
    op.create_index(op.f('ix_ocr_results_prescription_id'), 'ocr_results', ['prescription_id'], unique=True)
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_ocr_results_prescription_id'), table_name='ocr_results')
    op.create_unique_constraint(op.f('ocr_results_prescription_id_key'), 'ocr_results', ['prescription_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chat_history_prescription_id'), table_name='chat_history')
    op.drop_index(op.f('ix_ai_results_prescription_id'), table_name='ai_results')
    op.create_unique_constraint(op.f('ai_results_prescription_id_key'), 'ai_results', ['prescription_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
